### ISSUE TITLE
Usage / helper text updates

### ISSUE THREAD

**Issue by yi2020** [indeni/dragoneye#21]
```
Usage: dragoneye [OPTIONS] COMMAND [ARGS]...

  Scan cloud account. Currently supported: AWS, Azure

Options:
  --help  Show this message and exit.

Commands:
  aws    Scan an AWS cloud account
  azure  Scan an Azure cloud account
```

If I somehow got here without going through the GitHub repo first, I don't know what `Scan cloud account` means. I propose updating this to: `Execute data-fetching API commands on a cloud account at a large scale quickly.` 

-------

Under `dragoneye aws`, the option `--scan-commands-path` is odd. It's not exactly an option, since it's a require parameter. Putting it under the list of options is confusing.

Also, `The name of your cloud account` should be changed to `The name of your cloud account, the default value is 'default'`

Re `output-path`: `Defaults to current working directory.` isn't true, it defaults to `account-data`, no?

Similar comments about `dragoneye azure`.

--------

`Unable to locate credentials` should be `Unable to locate credentials. For AWS, we recommend providing the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables (and AWS_SESSION_TOKEN if needed). You may also choose to use the '--profile' option instead.`

--------

**Comment by Tomerva** [comment]
about scan-commands-path:
i can do one of 2 things:
1. Keep it a required option. Downside - confusing terminology
2. Make it a positional argument. Downside - no help message. To add description to this argument, we will need to add text to the command help (IE, aws / azure)

example of #2:
![image](https://user-images.githubusercontent.com/10116471/115150461-2f491780-a071-11eb-9a05-0d2b949f3c50.png)

**Comment by Tomerva** [comment]
about output-path:
the file structure is {output_path}/account-data/{account-name}

and if you do not provide output_path, then it will be equal to the current working directory

**Comment by yi2020** [comment]
About scan-commands-path - I prefer your second option.
Regarding output-path - the usage needs to clarify that.

In addition, another messaging issue:
```
will try to assume role using ARN: <arn redcated> and external id asdfasdfasdf
```

Should use capital `W`, and also a success or error message after attempting it. Also, messages that are in progress should have `...` at the end.
