### ISSUE TITLE
[Question] Azure Application Permissions for this solution

### ISSUE THREAD

**Issue by jonrau1** [indeni/dragoneye#92]
Hello folks -

Wonder what scopes/permissions are needed for an Azure AD Application to use this solution? I assume that this will retrieve all resources for Azure Resource Graph / Manager? Want to make sure I don't give an App too many / too little.

Thanks in advance!

**Comment by Tomerva** [comment]
Hi Jon,

the SP requires the Reader role, as it only scans for existing resources and not modifying or creating new one's.
You can use this terraform to create the SP for you:

provider "azuread" {
  version = "1.4.0"
}

variable "subscription_id" {
  description = "The subscription_id"
  type        = string
}

resource "azuread_application" "auth" {
  display_name = "cloudrail-gateway"
}

resource "azuread_service_principal" "auth" {
  application_id = azuread_application.auth.application_id
}

resource "random_string" "password" {
  length = 35
  special = false
}

resource "azuread_service_principal_password" "auth" {
  service_principal_id = azuread_service_principal.auth.id
  value                = random_string.password.result
  end_date             = "2299-12-30T23:00:00Z"
}

provider "azurerm" {
  version = "2.54.0"
  features {}
}

data "azurerm_subscription" "primary" {
  subscription_id = var.subscription_id
}

data "azurerm_client_config" "current" {}

resource "azurerm_role_assignment" "auth" {
  scope                = data.azurerm_subscription.primary.id
  role_definition_name = "Reader"
  principal_id         = azuread_service_principal.auth.id
}

output "tenant_id" {
  value = data.azurerm_client_config.current.tenant_id
  description = "Tenant Id"
}

output "subscription_id" {
  value = var.subscription_id
  description = "Subscription Id"
}

output "client_id" {
  value = azuread_application.auth.application_id
  description = "Client Id"
}

output "client_secret" {
  value = random_string.password.result
  description = "Client Secret"
}

**Comment by jonrau1** [comment]
@Tomerva awesome thank you! As far as the YAML - do you have an example to get *all* Azure resources? Is there an easy way to do that?

**Comment by Tomerva** [comment]
@jonrau1 I dont know of such a way, nor do i think Azure will provide that.
If there is such a way, it should be documented here: https://docs.microsoft.com/en-us/rest/api/azure/
